/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ChainlinkFeed, ChainlinkFeedInterface } from "../ChainlinkFeed";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class ChainlinkFeed__factory {
  static readonly abi = _abi;
  static createInterface(): ChainlinkFeedInterface {
    return new utils.Interface(_abi) as ChainlinkFeedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChainlinkFeed {
    return new Contract(address, _abi, signerOrProvider) as ChainlinkFeed;
  }
}
